AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvTag:
    Type: String

Outputs:
  WebSiteBucketName:
    Value: !Ref WebSiteBucket
  WebSiteUrl:
    Value: !GetAtt WebSiteBucket.WebsiteURL

Resources:
  WebSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvTag}-7498770b4dae"
      WebsiteConfiguration:
        IndexDocument: index.html
