version: 0.2

env:
  variables:
    GREETING: hello world!

phases:
  build:
    commands:
      - cd aws-ci-experiment
      - pwd
      - ls -la .
      - ./build.sh

artifacts:
  files:
    - index.html
  discard-paths: yes
