version: 0.2

env:
  variables:
    GREETING: hello world!

phases:
  build:
    commands:
      - cd aws-ci-experiment
      - chmod +x ./build.sh
      - ./build.sh

artifacts:
  files:
    - aws-ci-experiment/index.html
  discard-paths: yes
