AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyBucketName:
    Type: String

Outputs:
  WebsiteURL:
    Value: !GetAtt DummyBucket.WebsiteURL

Resources:
  DummyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Ref: MyBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete
