version: '3.1'

services:
  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - ./.data/minio:/data
    environment:
      MINIO_ACCESS_KEY: dummyaccesskey
      MINIO_SECRET_KEY: dummysecretkey
    ports:
      - 9000:9000
    command: server /data
