AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EcrRepositoryName:
    Type: String

Outputs:
  RepositoryName:
    Value: !Ref EcrRepository
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepositoryName"
  RepositoryUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepository}"

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepositoryName
