AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  PipelineBucketName:
    Value: !Ref PipelineBucket

Resources:
  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: ServiceName
          Value: '{{ service.name }}'
        - Key: ServiceBranch
          Value: '{{ service.branch_name }}'
        - Key: ServiceRepoConnectionArn
          Value: '{{ service.repository_connection_arn }}'
        - Key: ServiceRepoConnectionId
          Value: '{{ service.repository_id }}'
        - Key: PipelineInputsHello
          Value: '{{ pipeline.inputs.hello }}'
        - Key: SIEnvBucketName
          Value: '{{ service_instances[0].environment.outputs.EnvironmentBucketName }}'
        - Key: SIInputsHello
          Value: '{{ service_instances[0].inputs.hello }}'
        - Key: SIName
          Value: '{{ service_instances[0].name }}'
        - Key: SIOutputs
          Value: '{{ service_instances[0].outputs.ServiceBucketName }}'

# Pipeline:
# {{pipeline|tojson}}

# Service:
# {{service|tojson}}
