AWSTemplateFormatVersion: 2010-09-09

Parameters:
  NamespaceName:
    Type: String
    Default: xxx.local
  DummyServiceName:
    Type: String
    Default: dummy-service

Outputs:
  NamespaceName:
    Value: !Ref NamespaceName
  ServiceName:
    Value: !Ref DummyServiceName
  ServiceId:
    Value: !Ref DummyService

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  DnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Ref NamespaceName
      Vpc: !Ref Vpc

  DummyService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      NamespaceId: !Ref DnsNamespace
      Name: !Ref DummyServiceName
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300

  DummyServiceInstanceA:
    Type: AWS::ServiceDiscovery::Instance
    Properties:
      ServiceId: !Ref DummyService
      InstanceId: instance-a
      InstanceAttributes:
        AWS_INSTANCE_IPV4: 5.6.7.8
        AWS_INSTANCE_PORT: 8765
