version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  build:
    commands:
      - export ENV_TAG=${CODEBUILD_WEBHOOK_HEAD_REF##*/}
      - echo "hello world! EnvTag=${ENV_TAG}"
