AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  BucketName:
    Value: !Ref Bucket
  ProtonServiceRoleArn:
    Value: !GetAtt ProtonServiceRole.Arn

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  ProtonServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: proton.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowEverything
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
