AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  BucketName:
    Value: !Ref Bucket
  ProtonServiceRoleArn:
    Value: !GetAtt ProtonServiceRole.Arn
  PipelineServiceRoleArn:
    Value: !GetAtt PipelineServiceRole.Arn

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  ProtonServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: proton.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowThings
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CancelUpdateStack
                  - cloudformation:ContinueUpdateRollback
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackDriftDetectionStatus
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResourceDrifts
                  - cloudformation:DescribeStacks
                  - cloudformation:DetectStackResourceDrift
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:ListChangeSets
                  - cloudformation:ListStackResources
                  - cloudformation:UpdateStack
                Resource: !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/AWSProton-*"
              - Effect: Allow
                NotAction:
                  - organizations:*
                  - account:*
                Resource: "*"
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia:
                      - cloudformation.amazonaws.com
              - Effect: Allow
                Action:
                  - organizations:DescribeOrganization
                  - account:ListRegions
                Resource: "*"
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia:
                      - cloudformation.amazonaws.com

  PipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: proton.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowThings
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CancelUpdateStack
                  - cloudformation:ContinueUpdateRollback
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackDriftDetectionStatus
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResourceDrifts
                  - cloudformation:DescribeStacks
                  - cloudformation:DetectStackResourceDrift
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:ListChangeSets
                  - cloudformation:ListStackResources
                  - cloudformation:UpdateStack
                Resource: !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/AWSProton-*"
              - Effect: Allow
                NotAction:
                  - organizations:*
                  - account:*
                Resource: "*"
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia:
                      - cloudformation.amazonaws.com
              - Effect: Allow
                Action:
                  - organizations:DescribeOrganization
                  - account:ListRegions
                Resource: "*"
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia:
                      - cloudformation.amazonaws.com
