AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  KmsKeyId:
    Value: !Ref KmsKey
  KmsKeyAlias:
    Value: !Ref KmsKeyAlias
  UserAAccessKeyId:
    Value: !Ref UserAAccessKey
  UserASecretAccessKey:
    Value: !GetAtt UserAAccessKey.SecretAccessKey

Resources:
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allow everything to root
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Effect: Allow
            Action: kms:*
            Resource: "*"
          - Sid: Allow decrypt to UserA
            Principal:
              AWS: !GetAtt UserA.Arn
            Effect: Allow
            Action:
              - kms:Decrypt
            Resource: "*"

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/mykey
      TargetKeyId: !Ref KmsKey

  UserA:
    Type: AWS::IAM::User

  UserAAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref UserA
