AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApplicationId:
    Type: String
  SegmentId:
    Type: String

Resources:
  Campaign:
    Type: AWS::Pinpoint::Campaign
    Properties:
      Name: DummyCampaign
      ApplicationId: !Ref ApplicationId
      MessageConfiguration:
        EmailMessage:
          Title: The Dummy Campaign
          HtmlBody: |
            <p>Hi {{Address}}!</p>
            <p>Your user ID is {{User.UserId}} and your platform is {{Demographic.Platform}}.</p>
            <p>The Dummy Campaign says hi. Here's a <a href="http://www.google.com">link</link>.</p>
      Schedule:
        StartTime: IMMEDIATE
      SegmentId: !Ref SegmentId
