version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - curl "https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip" -o "terraform.zip" &&
        unzip -q terraform.zip -d /usr/local/bin
      - export PATH="/usr/local/bin:${PATH}"

  build:
    commands:
      - cd eks-experiment
      - ./gradlew clean bootJar
      - >
        envTag=${ENV_TAG}
        ./tool.sh deploy-layer3
