version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - export ENV_TAG=${CODEBUILD_WEBHOOK_HEAD_REF##*/}
      - echo "hello world! EnvTag=${ENV_TAG}"
